from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from datetime import datetime


class HealthCheckResponse(BaseModel):
    status: str
    rag_system: str
    models_loaded: bool


class SourceInfo(BaseModel):
    title: str
    page: Optional[int]
    relevance: float
    type: Optional[str]


class QuestionnaireResponse(BaseModel):
    risk_score: float = Field(..., description="Raw risk score (0-100)")
    normalized: float = Field(..., description="Normalized 0-1 risk")
    interpretation: str = Field(..., description="Human-friendly interpretation (low/medium/high)")
    summary: Optional[str] = Field(None, description="Brief clinical summary generated by RAG/LLM")
    details: Optional[Dict[str, Any]] = Field(None, description="Additional structured details")
    sources: List[SourceInfo] = Field(default_factory=list)
    created_patient_id: Optional[str] = Field(None, description="ID of the newly created patient if applicable")


class QueryResponse(BaseModel):
    answer: str
    evidence: List[Dict[str, Any]] = Field(default_factory=list)
    confidence: float = 0.0
    query_type: Optional[str] = None
    patient_context_used: bool = False
    explanations: Optional[Dict[str, Any]] = None


class EvaluationMetrics(BaseModel):
    precision: float
    recall: float
    mrr: float
    ndcg: float
    coherence: float
    relevance: float
    completeness: float
    citations: int
    lexical_diversity: float
    readability: float

class PatientOut(BaseModel):
    id: str
    name: str
    age: Optional[int] = None
    sex: Optional[str] = None
    education_level: Optional[str] = None
    years_of_education: Optional[int] = None
    medical_history: Optional[str] = None
    family_history: Optional[str] = None
    mse: Optional[float] = None
    moca: Optional[float] = None
    mmse_score: Optional[float] = None  # Alternative field name for mse
    moca_score: Optional[float] = None  # Alternative field name for moca
    symptoms_list: Optional[List[str]] = None
    biomarkers: Optional[Dict[str, Any]] = None
    imaging_findings: Optional[str] = None
    neuro_exam_notes: Optional[str] = None
    metrics: Optional[Dict[str, Any]] = None
    created_at: Optional[datetime] = None

class MRIAnalysisResponse(BaseModel):
    prediction_class: str = Field(..., description='Predicted class label')
    confidence: float = Field(..., description='Confidence score (0-1)')
    probabilities: Dict[str, float] = Field(..., description='Probabilities for all classes')
    class_index: int = Field(..., description='Index of predicted class')
    image_url: Optional[str] = Field(None, description='URL to uploaded MRI image')
    patient_id: Optional[str] = Field(None, description='Associated patient ID')
    analyzed_at: Optional[datetime] = Field(None, description='Timestamp of analysis')
